apiVersion: apps/v1
kind: Deployment
metadata:
  name: datetime-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datetime-app
  template:
    metadata:
      labels:
        app: datetime-app
    spec:
      containers:
      - name: my-container
        image: docker.io/baibhav225/datetime-app:dev
        ports:
        - containerPort: 9090
      imagePullSecrets:
      - name: regcred
